import { Helmet } from "react-helmet-async";

const content: Record<string, { title: string; intro: string; sections: Array<[string, string]> }> = {
  "/about": {
    title: "About RWDNEWS",
    intro: "RWDNEWS is a source-backed global news briefing platform built to help readers understand what is happening without drowning in noise.",
    sections: [
      ["What we do", "We discover current reports from publishers and open news sources, then present concise briefings with source attribution. RWDNEWS does not replace the original publisher."],
      ["AI-assisted, not AI-invented", "Automation may help classify, summarize, and organize reports. We instruct our systems to use supplied source material and avoid inventing facts. Readers can open the original report for full context."],
      ["Corrections", "If you spot an attribution, factual, image, or editorial problem, contact the RWDNEWS team so it can be reviewed and corrected."],
    ],
  },
  "/editorial": {
    title: "Editorial standards",
    intro: "RWDNEWS is designed around a simple rule: source first, context second, automation third.",
    sections: [
      ["Source-backed coverage", "Stories are discovered from publisher feeds and open news indexes. A developing item can be labeled as developing rather than presented as established fact."],
      ["Attribution", "Publisher names and original links are kept visible. RWDNEWS briefings are summaries, not a substitute for the source report."],
      ["No fabricated breaking news", "When the live wire is unavailable, the site does not quietly fill the feed with made-up headlines."],
      ["Images", "Images supplied by publishers are attributed. Where an editorial image is generated by RWDNEWS, that is disclosed. Commercial image rights are reviewed before paid use."],
    ],
  },
  "/privacy": {
    title: "Privacy",
    intro: "RWDNEWS collects only the information needed to operate the service, understand aggregate engagement, receive newsletter signups, and respond to advertising inquiries.",
    sections: [
      ["Newsletter", "If you subscribe, your email is stored for newsletter purposes. Do not submit sensitive personal information through newsletter or advertising forms."],
      ["Analytics", "RWDNEWS records lightweight events such as article opens, shares, saves, newsletter signups, and advertising inquiries. The product analytics table is designed without names or email addresses."],
      ["Advertising", "Third-party advertising may use cookies or similar technologies according to the provider's policies. Global advertising requires appropriate consent and disclosure controls."],
      ["Your choices", "You may unsubscribe from newsletters and use browser privacy controls. For privacy questions or deletion requests, contact the RWDNEWS operator through the advertised business contact channel."],
    ],
  },
  "/terms": {
    title: "Terms",
    intro: "By using RWDNEWS, you agree to use the service lawfully and understand that briefings are provided for general information.",
    sections: [
      ["Content", "RWDNEWS aggregates and summarizes reports from third-party sources. Original publishers retain their rights in their material."],
      ["No guarantee", "We work to keep information accurate and current, but news can change quickly and automated systems can make mistakes. Verify consequential information with primary sources."],
      ["Third-party links", "Links to publisher, sponsor, affiliate, or advertiser sites lead to third-party services governed by their own terms and policies."],
    ],
  },
  "/advertise": {
    title: "Advertise with RWDNEWS",
    intro: "RWDNEWS offers clearly disclosed advertising inventory for brands that want to reach readers interested in global news, technology, business, Africa, and emerging trends.",
    sections: [
      ["Available inventory", "Display advertising, sponsored placements, newsletter sponsorships, and selected homepage inventory can be offered subject to availability and editorial standards."],
      ["Editorial separation", "Paid placements are labeled. Advertising does not buy a favorable editorial position or change the source-backed news standard."],
      ["Request the media kit", "Use the Advertise button on the homepage to submit a business inquiry. The admin team can review leads, inventory, and sponsor placements."],
    ],
  },
};

export function InfoPage({ path }: { path: string }) {
  const page = content[path] || content["/about"];
  return (
    <div className="min-h-dvh bg-white text-neutral-950">
      <Helmet>
        <title>{page.title} — RWDNEWS</title>
        <meta name="description" content={page.intro} />
      </Helmet>
      <header className="border-b border-neutral-200">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-4 py-5 sm:px-6">
          <a href="/" className="font-display text-2xl font-bold">RWDNEWS</a>
          <a href="/" className="text-sm font-semibold text-teal-800">Back to news</a>
        </div>
      </header>
      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
        <p className="text-[10px] font-bold tracking-[0.18em] text-amber-800 uppercase">RWDNEWS</p>
        <h1 className="font-display mt-2 text-4xl font-semibold">{page.title}</h1>
        <p className="mt-4 text-lg leading-relaxed text-neutral-600">{page.intro}</p>
        <div className="mt-10 space-y-8">
          {page.sections.map(([heading, body]) => (
            <section key={heading}>
              <h2 className="font-display text-xl font-semibold">{heading}</h2>
              <p className="mt-2 leading-relaxed text-neutral-700">{body}</p>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
