-- RockBrief News Bot Phase F: performance feedback loop
alter table public.bot_story_candidates
  add column if not exists performance_score numeric(6,2) not null default 0;

create index if not exists bot_story_candidates_performance_idx
  on public.bot_story_candidates (performance_score desc, updated_at desc);

create table if not exists public.bot_story_performance (
  id bigint generated by default as identity primary key,
  article_id text not null references public.articles(id) on delete cascade,
  window_start timestamptz not null,
  page_views bigint not null default 0,
  article_opens bigint not null default 0,
  shares bigint not null default 0,
  saves bigint not null default 0,
  engaged_reads bigint not null default 0,
  return_visits bigint not null default 0,
  social_sent bigint not null default 0,
  social_failed bigint not null default 0,
  engagement_rate numeric(8,4) not null default 0,
  delivery_rate numeric(8,4) not null default 0,
  performance_score numeric(6,2) not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(article_id, window_start)
);

create index if not exists bot_story_performance_score_idx
  on public.bot_story_performance (performance_score desc, updated_at desc);

create index if not exists bot_story_performance_article_idx
  on public.bot_story_performance (article_id, updated_at desc);

alter table public.bot_story_performance enable row level security;

-- No public read/write policies: service-role bot access only.
